### ISSUE TITLE
В задачах с Python предоставлять все ресурсы для скачивания на локальную машину

### ISSUE THREAD

**Issue by pelid** [devmanorg/devman_v2#1]
Станислав Стёпин <stanislavalex@mail.ru>
> Если необходимо запустить код локально на ПК, то файл sales_log.json будет недоступен в задаче из модуля Основы Python.
> Не знаю как делает большинство, но я сначала пишу код локально, а потом запускаю на сайте. Поэтому и предложил сделать файл доступным для скачивания.

**Comment by pelid** [comment]
Насколько знаю, большинство пишет код во встроенном редакторе.

Ситуация понятна. Если наберется много голосов за эту "фичу", то сделаем. Голосуйте.

**Comment by vergeev** [comment]
Как временное решение, будем предоставлять ссылку на Яндекс Диск с материалами в первом шаге задачи. Потом посмотрим, как это лучше интегрировать в интерфейс.

Сейчас мы выложили файлы для «Основ Питона», и выглядит это так: 
<img width="332" alt="screenshot 2018-10-22 at 10 42 24" src="https://user-images.githubusercontent.com/13587415/47282276-41a08280-d5e7-11e8-88ff-986137b54586.png">

Если это будет актуально для других модулей, сделаем для них так же.
