### ISSUE TITLE
Счетчик количества попыток

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#10]
Вне зависимости от количества раз, которое я отправлял задачу на проверку, я всегда вижу сколько людей сдает со второй.

![image](https://user-images.githubusercontent.com/28685772/47216833-f13ee000-d3ae-11e8-848b-7a2a14cccad3.png)

Есть предложение изменить логику отображения.
У каждого пользователя на каждую задачу есть счетчик попыток.
Каждый раз когда вы отправляете на проверку, счетчик инкриминируется на +1
Есть общее количество людей, которые успешно сдали эту задачу.

Далее в главном меню (прим):
`N попытка(ток) чтобы сдать понадобилась % учеников`
ИЛИ
`С N попытки эту задачу сдают % учеников`

**Comment by vergeev** [comment]
У нас такая логика есть, но мы забыли её тут подключить. Убрал эту надпись до тех пор, пока мы не починим это поведение (на сайте она исчезнет в течение дня).

**Comment by vergeev** [comment]
В новом дизайне убрали счётчик в принципе. Вот и баг исправился
