### ISSUE TITLE
Работы на проверке

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#11]
Кейс. Я отправил работу на проверку преподавателю, он ее проверил.
В главном меню я вижу вот это:
![image](https://user-images.githubusercontent.com/28685772/47217309-a02feb80-d3b0-11e8-8561-34bb1980168e.png)

Исходя из этого, я не могу понять, моя работа проверена и принята, или там есть моменты, которые надо исправить.
Если моя работа принята (как например, на картинке, обе работы приняты и выполнены), то отображение их в статусе "Работы на проверке" не верно, они же уже проверены.

Мб стоит добавить значек статуса (знак восклицания, зеленая галочка), чтобы было более наглядно. `"Работа проверена преподавателем, требуется испрвление"` или `"Работа проверена преподавателем, принято"`

**Comment by vergeev** [comment]
Кажется, мы с @pelid обсуждали это, но не пришли к чему-то конкретному.

Как быстрый фикс, предлагаю разделить «Работы на проверке» на «Сданные работы», «Проверенные работы» и «Работы на проверке» (сейчас все три категории попадают в одну).

**Comment by SimonOsipov** [comment]
В добавлении к этому, скорее всего.
Если я сделал все задачи из модуля, у меня отображается, что модуль пройден:
![image](https://user-images.githubusercontent.com/28685772/47499646-2349b980-d869-11e8-9e07-3af70934828f.png)

Однако задача висит как "Задача на проверке" (и уже проверена и отмечена, что все верно)
![image](https://user-images.githubusercontent.com/28685772/47499674-365c8980-d869-11e8-9532-b0842ad06ca9.png)

**Comment by vergeev** [comment]
Спасибо, закинули в беклог.

**Comment by pelid** [comment]
Пиктограммы для разных итогов проверки - сдано или нет - вводить не будем. Это фича дизайна.

А вот заголовок "Задачи на проверке" стоит поменять. Пока самый удачный вариант из обсуждавшихся - это "Последние задачи". В нем будут отображаться также начатые, но ещё не отправленные на поверку задачи.

**Comment by vergeev** [comment]
Переименовал в «Последние задачи» заранее, чтобы самим не путаться.

**Comment by vergeev** [comment]
Теперь в раздел «Последние задачи» показывает только задачи, на которые пользователю не пофиг
