### ISSUE TITLE
Неполный вывод информации

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#12]
Python, Основы, урок 2. Считаем статистику продаж, шаг 7.
Задание говорит, что в результате работы программы я должен увидеть только 2 строчки:
![screenshot from 2018-10-20 11-06-30](https://user-images.githubusercontent.com/28685772/47253170-8944d400-d458-11e8-87c3-c3d035213f1a.png)

Но на деле я же вижу всю статистику из JSON
![screenshot from 2018-10-20 11-09-17](https://user-images.githubusercontent.com/28685772/47253177-9c57a400-d458-11e8-9d3e-665d4dc929cf.png)

Возможно, такое несовпадение кого-то может смутить: как это, мне говорят, что я должен увидеть только 2 строчки, а вижу все.

**Comment by vergeev** [comment]
Известная проблема: в некоторых местах у нас указан пример вывода, в некоторых — чётко то, что должно появиться на экране. В новых модулях мы явно указываем, что есть что, но в готовых задачах такие проблемы остались.

Поменял текст:
<img width="332" alt="screenshot 2018-10-22 at 09 29 33" src="https://user-images.githubusercontent.com/13587415/47280019-fe411680-d5dc-11e8-8edd-2dd263902dd1.png">

Если всё ок, тикет можно закрыть.
