### ISSUE TITLE
Якорь при переходе на доработанную задачу

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#13]
Дано:
Задача, отправлена на проверку, куратор дал комментарии, ошибки исправлены и снова отправлены на проверку.
Конкретно в данном случае модуль "Python", задача - Считаем статистику продаж.

В главном меню:
![image](https://user-images.githubusercontent.com/28685772/47554117-492a9900-d911-11e8-9fce-3ad86dfbe440.png)

Когда нажимаешь посмотреть, якорь идет на **#review-tabs**:
![image](https://user-images.githubusercontent.com/28685772/47554165-6495a400-d911-11e8-9f48-641fcfe5868c.png)

Меня смутил этот момент, я вновь увидет комментарии от куратора и полез разбираться, что не так, пришлось даже писать на емейл.
Однако лишь сегодня сообразил, что задача то решена:
![image](https://user-images.githubusercontent.com/28685772/47554213-87c05380-d911-11e8-98c4-875ec311b2c8.png)

Возможно, в рамках улучшения UX, стоит делать якорь на "Задача решена" (пример ниже):
![image](https://user-images.githubusercontent.com/28685772/47554268-a3c3f500-d911-11e8-9b57-78df1295f00b.png)

**Comment by vergeev** [comment]
Поправлено, спасибо.
