### ISSUE TITLE
Унификация языка терминологии

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#15]
В описании y некоторых модулей вы используете английский язык для терминов и команд. Пример:
![screenshot from 2018-10-29 22-32-35](https://user-images.githubusercontent.com/28685772/47675302-9d13d700-dbca-11e8-89ca-ff9b584b1285.png)
или
![screenshot from 2018-10-29 22-32-28](https://user-images.githubusercontent.com/28685772/47675316-aa30c600-dbca-11e8-9705-d07b3cffcfea.png)

Однако в модуле про GitHub использется русский язык и перевод терминов. Возможно, стоит использовать англоязычные commit, fork, branch, clone и так далее.
![screenshot from 2018-10-29 22-30-17](https://user-images.githubusercontent.com/28685772/47675356-c896c180-dbca-11e8-9e7a-824c3195ef8b.png)

**Comment by vergeev** [comment]
Возможно, нам и стоит ввести универсальное правило по поводу того, что показывается на карточке модуля, но из примера это не понятно. 

В модулях про Linux сервер и командную строку перечислены освещаемые в модуле команды, в модуле про Git и Github — понятия и действия. Дело в том, что Git и Github не про консольный git, и если бы мы написали `clone`, `git log` или вроде того, то могли бы ввести пользователей в заблуждение.

На этом этапе не вижу большой разницы, что указывать: команды или понятия, лишь бы отражалось содержимое модуля.
