### ISSUE TITLE
Отображать статус последних задач

### ISSUE THREAD

**Issue by nicko858** [devmanorg/devman_v2#18]
Сейчас не отображается статус последних задач. Только если явно не кликнуть по задаче:

![image](https://user-images.githubusercontent.com/35272808/48133766-f786f480-e2a8-11e8-8aca-4b2ed2b925d0.png)

Было бы интересно отображать статус задач с цветом. Типа зелененькая-решена, красная -доработать.

**Comment by SimonOsipov** [comment]
Более подробное обсуждение данного момента есть вот здесь https://github.com/devmanorg/devman_v2/issues/11

**Comment by vergeev** [comment]
Нужно что-то доработать или нет скрывается нарочно. Когда-нибудь я уговорю @pelid так не делать, но пока wontfix.
