### ISSUE TITLE
Посмотреть уже пройденный урок

### ISSUE THREAD

**Issue by pelid** [devmanorg/devman_v2#19]
> А как мне посмотреть те уроки, что я уже прошел? Я кое что хотел перечитать в одном из уроков..

Нужны подробности. Что понадобилось из ранее пройденного урока? Ссылки на статьи? Слайды?

**Comment by SimonOsipov** [comment]
Конкретный момент: я пытался вспомнить, как задавать переменные окружения. Я мог полезть в гугл, но я помнил, что были слайды / статьи в одном из уроков по командной строке. Однако открыть прошлые уроки не смог, полез в гугл.

Наверное, если бы слайды / ссылки на статьи были доступны после окончания модуля - было бы шикарно.
Слайды то хорошие.

**Comment by timerminator** [comment]
Хочется видеть что-то вроде базы знаний как в первом девмане. И сами задачи, если есть такая возможность.

**Comment by vergeev** [comment]
dvmn.org/archive
