### ISSUE TITLE
В списке "Последние задачи" висят пройденные уроки, убрать которые невозможно

### ISSUE THREAD

**Issue by pelid** [devmanorg/devman_v2#20]
> В списке "Последние задачи" висят пройденные уроки, убрать которые невозможно. Было бы хорошо, если такая возможность появится.

**Скриншоты**

![image](https://user-images.githubusercontent.com/870324/48914525-bd167d80-ee8c-11e8-888f-536d0108b954.png)

**Comment by vergeev** [comment]
Теперь они убираются при просмотре страницы урока
