### ISSUE TITLE
Недоступность wttr.in

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#21]
**Описание**
Задачу 1 из модуля по API нельзя выполнить потому, что сервис http://wttr.in бывает недоступен, так как у них более 1М запросов в день.

**Как ее повторить**
Что нужно сделать, чтобы воспроизвести данную ошибку:
1. Перейти на http://wttr.in
2. Увидеть ошибку:
![image](https://user-images.githubusercontent.com/28685772/48937348-dd8f1800-ef1e-11e8-8baa-0a2584ad58da.png)

**Как должно работать**
А сервис должен выдавать погоду. Возможнос, стоит написать предупреждение где-нибудь в тексе задания, что такое может случиться.

**Comment by vergeev** [comment]
Сейчас посмотрим, сможем ли мы его поднять у себя.

**Comment by vergeev** [comment]
Сейчас wttr.in снова стал доступен. Скоро запустим бекап-сервис.

**Comment by vergeev** [comment]
Наконец-то запустили: http://wttr.dvmn.org/moscow

Потихоньку внедрим его в задачи.
