### ISSUE TITLE
Кривое отображение при рассылке подтверждения на подписку

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#22]
**Описание**
При подписке на выход нового модуля приходит подтверждение. В подтверждении проблема с дизайном кнопки

**Скриншоты**
![screenshot_20181127-135729_email](https://user-images.githubusercontent.com/28685772/49077976-cf5a3800-f24d-11e8-9490-41b6648ec57c.jpg)

**Дополнительно**
"Вашу подписку на нашу рассылку" надо убрать из элемента "Кнопка"

**Comment by vergeev** [comment]
А это дефолтная вёрстка Mailchimp. В большинстве случаев она не едет, поэтому пусть будет.

Потом как-нибудь выкатим свою (которая коне-е-ечно же будет идеальной).
