### ISSUE TITLE
Аргументы командной строки

### ISSUE THREAD

**Issue by nicko858** [devmanorg/devman_v2#24]
**Описание**
В Уроке 4. Получаем статистику из MP3-тегов - хорошо бы реализовать добавление аргументов "руками".

**Как должно работать**
В select-box запуска скрипта можно добавить текстовое поле для внесения аргументов.

**Скриншоты**
![image](https://user-images.githubusercontent.com/35272808/49648246-1b6b6080-fa36-11e8-84fc-7e3241318dfc.png)

**Система:**
 - Система:  Linux
 - Браузер chrome

**Comment by pelid** [comment]
Интересная идея. После небольшого рефакторинга это возможно реализовать.

**Comment by vergeev** [comment]
Модуль «Основы Python» отправился в утиль. Думаю, во встроенном терминале не будет настолько сложных задач, чтобы понадобилось использовать argparse.
