### ISSUE TITLE
Время работы преподавателя

### ISSUE THREAD

**Issue by MrStepin** [devmanorg/devman_v2#3]
Станислав Стёпин stanislavalex@mail.ru
Добавить информацию о том, что преподаватель не работает по выходным. 
Когда отправляешь задание на проверку в пятницу вечером, робот пишет, что осталось ждать меньше одного дня, а по факту больше двух дней.(до утра понедельника)

**Comment by pelid** [comment]
Исправлено. Указано что проверка работ производится по рабочим дням.

https://goo.gl/rDZKEr
https://goo.gl/DrDsHC
