### ISSUE TITLE
Linux терминал в модуле командная строка работает не стабильно

### ISSUE THREAD

**Issue by MrStepin** [devmanorg/devman_v2#5]
При запуске Linux терминал в модуле командная строка периодически вместо запуска терминала появляется ошибка "404 not found" и приходится несколько раз перезапускать браузер или обновлять страницу чтобы терминал заработал. 
Используемые браузеры: Chrome 69.0.3497.100;  Edge 42.17134.1.0

**Comment by pelid** [comment]
Выяснили причину. Как временное решение - помогает обновление страницы браузера по нажатию F5.

Запланировали исправление ошибки. По готовности отпишусь.

**Comment by pelid** [comment]
исправлено
