### ISSUE TITLE
Добавить кнопку отзыва работы с проверки.

### ISSUE THREAD

**Issue by mikhail-akimov** [devmanorg/devman_v2#6]
Проблема:
Уже не в первый раз по тем или иным причинам я, нажав кнопку "Сдать работу на проверку" понимаю, что версия кода в веб-интерпретаторе не то, что я хотел сдать (либо не все задания доделал и не заметил, либо делал задание локально, либо "причесать" код забыл и т.п.). 
Сейчас приходится обращаться к преподавателю, чтобы он вернул задание досрочно, чтобы я мог его доделать (не хочется отдавать на проверку то, что заранее не соответствует требуемому качеству и ты сам знаешь в чём). 

Решение:
Сделать кнопку "Отозвать работу", которой можно было бы вернуть самому себе задание на доработку. Можно сделать её доступной определённое количество времени (не 10 секунд, конечно, как в гугл-почте).

**Comment by pelid** [comment]
С технической точки зрения это нетривиальная "фича". Но ситуация со случайной отправкой кода встречалась уже несколько раз. Будем думать как реализовать.

**Comment by vergeev** [comment]
Спасибо, что подождали. 

Отзывать своё решение теперь можно:

<img width="674" alt="screenshot 2018-10-20 at 13 21 35" src="https://user-images.githubusercontent.com/13587415/47254534-6c1a0080-d46c-11e8-9253-838fea7244a7.png">

Если заметите ещё какие-то неудобства или ошибки в работе сайта — пишите, будем рады.
