### ISSUE TITLE
Смешанное отображение на слайдах

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#7]
Слайд № 5 на "[Зачем нужен ifmain](https://slides.com/vergeev/ifmain/#/4)"
![screenshot from 2018-10-17 07-21-17](https://user-images.githubusercontent.com/28685772/47062155-488d5680-d1dd-11e8-9241-94e3565f0a1b.png)

ifmain_print.py отображается поверх кода.

**Comment by vergeev** [comment]
Спасибо, исправили
