### ISSUE TITLE
[bug] Ссылка на несуществующий модуль

### ISSUE THREAD

**Issue by SimonOsipov** [devmanorg/devman_v2#9]
Блок [Git и Github](https://dvmn.org/modules/git-github/)
Рекомендует начать подготовку с более простых модулей:
![screenshot from 2018-10-18 22-15-39](https://user-images.githubusercontent.com/28685772/47178360-b04db980-d323-11e8-8f33-69bf6d053b6a.png)

Однако такого модуля не существует. 
Ссылка ведет на https://dvmn.org/modules/command-line/module-router/, редиректит на список модулей.

**Comment by vergeev** [comment]
Мигрируем модули, недосмотрели. Исправили.

Большое спасибо!
